package org.iesvdm.jardineria.modelo;
// Generated 3 dic 2023 12:28:04 by Hibernate Tools 5.6.15.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	private int codigoCliente;
	private Empleado empleado;
	private String nombreCliente;
	private String nombreContacto;
	private String apellidoContacto;
	private String telefono;
	private String fax;
	private String lineaDireccion1;
	private String lineaDireccion2;
	private String ciudad;
	private String region;
	private String pais;
	private String codigoPostal;
	private BigDecimal limiteCredito;
	private Set pedidos = new HashSet(0);
	private Set<Pago> pagos = new HashSet<>(0);

	public Cliente() {
	}

	public Cliente(int codigoCliente, String nombreCliente, String telefono, String fax, String lineaDireccion1,
			String ciudad) {
		this.codigoCliente = codigoCliente;
		this.nombreCliente = nombreCliente;
		this.telefono = telefono;
		this.fax = fax;
		this.lineaDireccion1 = lineaDireccion1;
		this.ciudad = ciudad;
	}

	public Cliente(int codigoCliente, Empleado empleado, String nombreCliente, String nombreContacto,
			String apellidoContacto, String telefono, String fax, String lineaDireccion1, String lineaDireccion2,
			String ciudad, String region, String pais, String codigoPostal, BigDecimal limiteCredito, Set pedidos,
			Set pagos) {
		this.codigoCliente = codigoCliente;
		this.empleado = empleado;
		this.nombreCliente = nombreCliente;
		this.nombreContacto = nombreContacto;
		this.apellidoContacto = apellidoContacto;
		this.telefono = telefono;
		this.fax = fax;
		this.lineaDireccion1 = lineaDireccion1;
		this.lineaDireccion2 = lineaDireccion2;
		this.ciudad = ciudad;
		this.region = region;
		this.pais = pais;
		this.codigoPostal = codigoPostal;
		this.limiteCredito = limiteCredito;
		this.pedidos = pedidos;
		this.pagos = pagos;
	}

	public int getCodigoCliente() {
		return this.codigoCliente;
	}

	public void setCodigoCliente(int codigoCliente) {
		this.codigoCliente = codigoCliente;
	}

	public Empleado getEmpleado() {
		return this.empleado;
	}
	public Empleado getRepresentanteVentas() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	public String getNombreCliente() {
		return this.nombreCliente;
	}

	public void setNombreCliente(String nombreCliente) {
		this.nombreCliente = nombreCliente;
	}

	public String getNombreContacto() {
		return this.nombreContacto;
	}

	public void setNombreContacto(String nombreContacto) {
		this.nombreContacto = nombreContacto;
	}

	public String getApellidoContacto() {
		return this.apellidoContacto;
	}

	public void setApellidoContacto(String apellidoContacto) {
		this.apellidoContacto = apellidoContacto;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getLineaDireccion1() {
		return this.lineaDireccion1;
	}

	public void setLineaDireccion1(String lineaDireccion1) {
		this.lineaDireccion1 = lineaDireccion1;
	}

	public String getLineaDireccion2() {
		return this.lineaDireccion2;
	}

	public void setLineaDireccion2(String lineaDireccion2) {
		this.lineaDireccion2 = lineaDireccion2;
	}

	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	public String getCodigoPostal() {
		return this.codigoPostal;
	}

	public void setCodigoPostal(String codigoPostal) {
		this.codigoPostal = codigoPostal;
	}

	public BigDecimal getLimiteCredito() {
		return this.limiteCredito;
	}

	public void setLimiteCredito(BigDecimal limiteCredito) {
		this.limiteCredito = limiteCredito;
	}

	public Set getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set pedidos) {
		this.pedidos = pedidos;
	}

	public Set<Pago> getPagos() {
		return this.pagos;
	}

	public void setPagos(Set<Pago> pagos) {
		this.pagos = pagos;
	}

	@Override
	public String toString() {
		return "Cliente{" +
				"codigoCliente=" + codigoCliente +
				", empleado=" + empleado +
				", nombreCliente='" + nombreCliente + '\'' +
				", nombreContacto='" + nombreContacto + '\'' +
				", apellidoContacto='" + apellidoContacto + '\'' +
				", telefono='" + telefono + '\'' +
				", fax='" + fax + '\'' +
				", lineaDireccion1='" + lineaDireccion1 + '\'' +
				", lineaDireccion2='" + lineaDireccion2 + '\'' +
				", ciudad='" + ciudad + '\'' +
				", region='" + region + '\'' +
				", pais='" + pais + '\'' +
				", codigoPostal='" + codigoPostal + '\'' +
				", limiteCredito=" + limiteCredito +
				'}';
	}
}
