package org.iesvdm.jardineria.modelo;
// Generated 3 dic 2023 12:28:04 by Hibernate Tools 5.6.15.Final

import java.math.BigDecimal;

/**
 * DetallePedido generated by hbm2java
 */
public class DetallePedido implements java.io.Serializable {

	private DetallePedidoId id;
	private Pedido pedido;
	private Producto producto;
	private int cantidad;
	private BigDecimal precioUnidad;
	private short numeroLinea;

	public DetallePedido() {
	}

	public DetallePedido(DetallePedidoId id, Pedido pedido, Producto producto, int cantidad, BigDecimal precioUnidad,
			short numeroLinea) {
		this.id = id;
		this.pedido = pedido;
		this.producto = producto;
		this.cantidad = cantidad;
		this.precioUnidad = precioUnidad;
		this.numeroLinea = numeroLinea;
	}

	public DetallePedidoId getId() {
		return this.id;
	}

	public void setId(DetallePedidoId id) {
		this.id = id;
	}

	public Pedido getPedido() {
		return this.pedido;
	}

	public void setPedido(Pedido pedido) {
		this.pedido = pedido;
	}

	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public BigDecimal getPrecioUnidad() {
		return this.precioUnidad;
	}

	public void setPrecioUnidad(BigDecimal precioUnidad) {
		this.precioUnidad = precioUnidad;
	}

	public short getNumeroLinea() {
		return this.numeroLinea;
	}

	public void setNumeroLinea(short numeroLinea) {
		this.numeroLinea = numeroLinea;
	}

	@Override
	public String toString() {
		return "DetallePedido{" +
				"id=" + id +
				", pedido=" + pedido +
				", producto=" + producto +
				", cantidad=" + cantidad +
				", precioUnidad=" + precioUnidad +
				", numeroLinea=" + numeroLinea +
				'}';
	}
}
