package org.iesvdm.jardineria.modelo;
// Generated 3 dic 2023 12:28:04 by Hibernate Tools 5.6.15.Final

/**
 * DetallePedidoId generated by hbm2java
 */
public class DetallePedidoId implements java.io.Serializable {

	private int codigoPedido;
	private String codigoProducto;

	public DetallePedidoId() {
	}

	public DetallePedidoId(int codigoPedido, String codigoProducto) {
		this.codigoPedido = codigoPedido;
		this.codigoProducto = codigoProducto;
	}

	public int getCodigoPedido() {
		return this.codigoPedido;
	}

	public void setCodigoPedido(int codigoPedido) {
		this.codigoPedido = codigoPedido;
	}

	public String getCodigoProducto() {
		return this.codigoProducto;
	}

	public void setCodigoProducto(String codigoProducto) {
		this.codigoProducto = codigoProducto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetallePedidoId))
			return false;
		DetallePedidoId castOther = (DetallePedidoId) other;

		return (this.getCodigoPedido() == castOther.getCodigoPedido())
				&& ((this.getCodigoProducto() == castOther.getCodigoProducto())
						|| (this.getCodigoProducto() != null && castOther.getCodigoProducto() != null
								&& this.getCodigoProducto().equals(castOther.getCodigoProducto())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoPedido();
		result = 37 * result + (getCodigoProducto() == null ? 0 : this.getCodigoProducto().hashCode());
		return result;
	}

	@Override
	public String toString() {
		return "DetallePedidoId{" +
				"codigoPedido=" + codigoPedido +
				", codigoProducto='" + codigoProducto + '\'' +
				'}';
	}
}
