package org.iesvdm.jardineria.modelo;
// Generated 3 dic 2023 12:28:04 by Hibernate Tools 5.6.15.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado implements java.io.Serializable {

	private int codigoEmpleado;
	private Empleado empleado;
	private Oficina oficina;
	private String nombre;
	private String apellido1;
	private String apellido2;
	private String extension;
	private String email;
	private String puesto;
	private Set<Empleado> empleados = new HashSet<>(0);
	private Set<Cliente> clientes = new HashSet<>(0);

	public Empleado() {
	}

	public Empleado(int codigoEmpleado, Oficina oficina, String nombre, String apellido1, String extension,
			String email) {
		this.codigoEmpleado = codigoEmpleado;
		this.oficina = oficina;
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.extension = extension;
		this.email = email;
	}

	public Empleado(int codigoEmpleado, Empleado empleado, Oficina oficina, String nombre, String apellido1,
			String apellido2, String extension, String email, String puesto, Set<Empleado> empleados, Set<Cliente> clientes) {
		this.codigoEmpleado = codigoEmpleado;
		this.empleado = empleado;
		this.oficina = oficina;
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.extension = extension;
		this.email = email;
		this.puesto = puesto;
		this.empleados = empleados;
		this.clientes = clientes;
	}

	public int getCodigoEmpleado() {
		return this.codigoEmpleado;
	}

	public void setCodigoEmpleado(int codigoEmpleado) {
		this.codigoEmpleado = codigoEmpleado;
	}

	public Empleado getEmpleado() {
		return this.empleado;
	}
	public Empleado getJefe() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	public Oficina getOficina() {
		return this.oficina;
	}

	public void setOficina(Oficina oficina) {
		this.oficina = oficina;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	public String getExtension() {
		return this.extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPuesto() {
		return this.puesto;
	}

	public void setPuesto(String puesto) {
		this.puesto = puesto;
	}

	public Set<Empleado> getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Set empleados) {
		this.empleados = empleados;
	}

	public Set<Cliente> getClientes() {
		return this.clientes;
	}

	public void setClientes(Set<Cliente> clientes) {
		this.clientes = clientes;
	}


	@Override
	public String toString() {
		return "Empleado{" +
				"codigoEmpleado=" + codigoEmpleado +
				", empleado=" + empleado +
				", oficina=" + oficina +
				", nombre='" + nombre + '\'' +
				", apellido1='" + apellido1 + '\'' +
				", apellido2='" + apellido2 + '\'' +
				", extension='" + extension + '\'' +
				", email='" + email + '\'' +
				", puesto='" + puesto + '\'' +
				'}';
	}
}
