package org.iesvdm.jardineria.modelo;
// Generated 3 dic 2023 12:28:04 by Hibernate Tools 5.6.15.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Oficina generated by hbm2java
 */
public class Oficina implements java.io.Serializable {

	private String codigoOficina;
	private String ciudad;
	private String pais;
	private String region;
	private String codigoPostal;
	private String telefono;
	private String lineaDireccion1;
	private String lineaDireccion2;
	private Set<Empleado> empleados = new HashSet<>(0);

	public Oficina() {
	}

	public Oficina(String codigoOficina, String ciudad, String pais, String codigoPostal, String telefono,
			String lineaDireccion1) {
		this.codigoOficina = codigoOficina;
		this.ciudad = ciudad;
		this.pais = pais;
		this.codigoPostal = codigoPostal;
		this.telefono = telefono;
		this.lineaDireccion1 = lineaDireccion1;
	}

	public Oficina(String codigoOficina, String ciudad, String pais, String region, String codigoPostal,
			String telefono, String lineaDireccion1, String lineaDireccion2, Set empleados) {
		this.codigoOficina = codigoOficina;
		this.ciudad = ciudad;
		this.pais = pais;
		this.region = region;
		this.codigoPostal = codigoPostal;
		this.telefono = telefono;
		this.lineaDireccion1 = lineaDireccion1;
		this.lineaDireccion2 = lineaDireccion2;
		this.empleados = empleados;
	}

	public String getCodigoOficina() {
		return this.codigoOficina;
	}

	public void setCodigoOficina(String codigoOficina) {
		this.codigoOficina = codigoOficina;
	}

	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	public String getCodigoPostal() {
		return this.codigoPostal;
	}

	public void setCodigoPostal(String codigoPostal) {
		this.codigoPostal = codigoPostal;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getLineaDireccion1() {
		return this.lineaDireccion1;
	}

	public void setLineaDireccion1(String lineaDireccion1) {
		this.lineaDireccion1 = lineaDireccion1;
	}

	public String getLineaDireccion2() {
		return this.lineaDireccion2;
	}

	public void setLineaDireccion2(String lineaDireccion2) {
		this.lineaDireccion2 = lineaDireccion2;
	}

	public Set<Empleado> getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Set<Empleado> empleados) {
		this.empleados = empleados;
	}

	@Override
	public String toString() {
		return "Oficina{" +
				"codigoOficina='" + codigoOficina + '\'' +
				", ciudad='" + ciudad + '\'' +
				", pais='" + pais + '\'' +
				", region='" + region + '\'' +
				", codigoPostal='" + codigoPostal + '\'' +
				", telefono='" + telefono + '\'' +
				", lineaDireccion1='" + lineaDireccion1 + '\'' +
				", lineaDireccion2='" + lineaDireccion2 + '\'' +
				'}';
	}
}
