package org.iesvdm.jardineria.modelo;
// Generated 3 dic 2023 12:28:04 by Hibernate Tools 5.6.15.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Pago generated by hbm2java
 */
public class Pago implements java.io.Serializable {

	private PagoId id;
	private Cliente cliente;
	private String formaPago;
	private Date fechaPago;
	private BigDecimal total;

	public Pago() {
	}

	public Pago(PagoId id, Cliente cliente, String formaPago, Date fechaPago, BigDecimal total) {
		this.id = id;
		this.cliente = cliente;
		this.formaPago = formaPago;
		this.fechaPago = fechaPago;
		this.total = total;
	}

	public PagoId getId() {
		return this.id;
	}

	public void setId(PagoId id) {
		this.id = id;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public String getFormaPago() {
		return this.formaPago;
	}

	public void setFormaPago(String formaPago) {
		this.formaPago = formaPago;
	}

	public Date getFechaPago() {
		return this.fechaPago;
	}

	public void setFechaPago(Date fechaPago) {
		this.fechaPago = fechaPago;
	}

	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	@Override
	public String toString() {
		return "Pago{" +
				"id=" + id +
				", cliente=" + cliente +
				", formaPago='" + formaPago + '\'' +
				", fechaPago=" + fechaPago +
				", total=" + total +
				'}';
	}
}
