package org.iesvdm.jardineria.modelo;
// Generated 3 dic 2023 12:28:04 by Hibernate Tools 5.6.15.Final

/**
 * PagoId generated by hbm2java
 */
public class PagoId implements java.io.Serializable {

	private int codigoCliente;
	private String idTransaccion;

	public PagoId() {
	}

	public PagoId(int codigoCliente, String idTransaccion) {
		this.codigoCliente = codigoCliente;
		this.idTransaccion = idTransaccion;
	}

	public int getCodigoCliente() {
		return this.codigoCliente;
	}

	public void setCodigoCliente(int codigoCliente) {
		this.codigoCliente = codigoCliente;
	}

	public String getIdTransaccion() {
		return this.idTransaccion;
	}

	public void setIdTransaccion(String idTransaccion) {
		this.idTransaccion = idTransaccion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PagoId))
			return false;
		PagoId castOther = (PagoId) other;

		return (this.getCodigoCliente() == castOther.getCodigoCliente())
				&& ((this.getIdTransaccion() == castOther.getIdTransaccion())
						|| (this.getIdTransaccion() != null && castOther.getIdTransaccion() != null
								&& this.getIdTransaccion().equals(castOther.getIdTransaccion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoCliente();
		result = 37 * result + (getIdTransaccion() == null ? 0 : this.getIdTransaccion().hashCode());
		return result;
	}

	@Override
	public String toString() {
		return "PagoId{" +
				"codigoCliente=" + codigoCliente +
				", idTransaccion='" + idTransaccion + '\'' +
				'}';
	}
}
