package org.iesvdm.jardineria.modelo;
// Generated 3 dic 2023 12:28:04 by Hibernate Tools 5.6.15.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

	private String codigoProducto;
	private GamaProducto gamaProducto;
	private String nombre;
	private String dimensiones;
	private String proveedor;
	private String descripcion;
	private short cantidadEnStock;
	private BigDecimal precioVenta;
	private BigDecimal precioProveedor;
	private Set detallePedidos = new HashSet(0);

	public Producto() {
	}

	public Producto(String codigoProducto, GamaProducto gamaProducto, String nombre, short cantidadEnStock,
			BigDecimal precioVenta) {
		this.codigoProducto = codigoProducto;
		this.gamaProducto = gamaProducto;
		this.nombre = nombre;
		this.cantidadEnStock = cantidadEnStock;
		this.precioVenta = precioVenta;
	}

	public Producto(String codigoProducto, GamaProducto gamaProducto, String nombre, String dimensiones,
			String proveedor, String descripcion, short cantidadEnStock, BigDecimal precioVenta,
			BigDecimal precioProveedor, Set detallePedidos) {
		this.codigoProducto = codigoProducto;
		this.gamaProducto = gamaProducto;
		this.nombre = nombre;
		this.dimensiones = dimensiones;
		this.proveedor = proveedor;
		this.descripcion = descripcion;
		this.cantidadEnStock = cantidadEnStock;
		this.precioVenta = precioVenta;
		this.precioProveedor = precioProveedor;
		this.detallePedidos = detallePedidos;
	}

	public String getCodigoProducto() {
		return this.codigoProducto;
	}

	public void setCodigoProducto(String codigoProducto) {
		this.codigoProducto = codigoProducto;
	}

	public GamaProducto getGamaProducto() {
		return this.gamaProducto;
	}

	public void setGamaProducto(GamaProducto gamaProducto) {
		this.gamaProducto = gamaProducto;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDimensiones() {
		return this.dimensiones;
	}

	public void setDimensiones(String dimensiones) {
		this.dimensiones = dimensiones;
	}

	public String getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(String proveedor) {
		this.proveedor = proveedor;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public short getCantidadEnStock() {
		return this.cantidadEnStock;
	}

	public void setCantidadEnStock(short cantidadEnStock) {
		this.cantidadEnStock = cantidadEnStock;
	}

	public BigDecimal getPrecioVenta() {
		return this.precioVenta;
	}

	public void setPrecioVenta(BigDecimal precioVenta) {
		this.precioVenta = precioVenta;
	}

	public BigDecimal getPrecioProveedor() {
		return this.precioProveedor;
	}

	public void setPrecioProveedor(BigDecimal precioProveedor) {
		this.precioProveedor = precioProveedor;
	}

	public Set getDetallePedidos() {
		return this.detallePedidos;
	}

	public void setDetallePedidos(Set detallePedidos) {
		this.detallePedidos = detallePedidos;
	}


	@Override
	public String toString() {
		return "Producto{" +
				"codigoProducto='" + codigoProducto + '\'' +
				", gamaProducto=" + gamaProducto +
				", nombre='" + nombre + '\'' +
				", dimensiones='" + dimensiones + '\'' +
				", proveedor='" + proveedor + '\'' +
				", descripcion='" + descripcion + '\'' +
				", cantidadEnStock=" + cantidadEnStock +
				", precioVenta=" + precioVenta +
				", precioProveedor=" + precioProveedor +
				'}';
	}
}
